### ISSUE TITLE
customisation not wokring

### ISSUE THREAD

**Issue by PatelMitun** [AlexandrGraschenkov/QRCodes#2]
Hello @AlexandrGraschenkov 

I check your QRCode library and get below issue like
1) When Input message size is more that 30 like 60 character or 100 character, then library is crashing.

> FILE: qr_data_coder.hpp, Line: 41

2) I want to change angle of QRCode, so I change code stop rotate while generate image and again it crashing and also not able to scan QRCode when any angles change.

> FILE: QRCodeDrawer.m, Line: 77

**Comment by AlexandrGraschenkov** [comment]
Hi @PatelMitun 

This demo was written in 4 evenings and I didn't have time to make it easy to change in some way. So I recommend to use this code as example code, cause even `ReedSolomon` not works properly(I found it on new custom QRs).

You can look on this algorithm as group of modules stitched together. We have: `control point detector`, `bits extractor`, `decoder\encoder+RS code correction`, `alphabet`, `qr code drawer`, `camera api`. For creating new custom code you more probably will have different layout. It will affect to `qr code drawer` and `bits extractor`. I recommend to adjust changes in this order: `alphabet`, `qr code drawer`. When you have desired result image with QR code, then move to mac os app project. You will also need to change `bits extractor`, cause your layout may be changed after changes in drawer. Other modules probably will work fine.

1) When you change number of symbols it affects to quality of `bits extractor`. When you perform changes in message size, you also need to change drawer. And after this change little bit `bits extractor`.

2) Everything works fine if you just comment this line. More probably something broken in orientation fix part in your code. 

**Please note**:  `decoder\encoder+RS code correction` works not properly in RS code correction. Better to change this module to different RS code correction. Correct RS correction solution will depends on alphabet size. Only google and experiments can help you. You can fix it after everything else will works. If `bits extractor` works properly, you will get correct message outside.


Good luck with your project, hope you will fix all bugs in your project.
