### ISSUE TITLE
'opencv2/core.hpp' file not found

### ISSUE THREAD

**Issue by rib3ye** [AlexandrGraschenkov/QRCodes#4]
<img width="1476" alt="Screen Shot 2022-02-24 at 3 42 57 PM" src="https://user-images.githubusercontent.com/590099/155625990-d3993833-6bb5-4147-acbc-a549b56c6db0.png">

Hi, I tried building in Xcode 13.2.1  today on macOS 12.1 but it failed because it's missing `opencv2/core.hpp`.

**Comment by AlexandrGraschenkov** [comment]
You need to instal OpenCV in your system for C++ usage. If you already done, change location of OpenCV library if necessary. It's `Headers search path` and `Library search path`.

![change_opncv_folder](https://user-images.githubusercontent.com/964601/156124546-f84b1af9-7e06-48dd-a4d4-978d4e277d5b.jpg)
